version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - 8806:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wapuugotchi

  wordpress:
    build: https://gitlab.git-wp.server.lan/wp-dev/wordpress-docker.git
    depends_on:
      - db
    ports:
      - 8076:80
    volumes:
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/plugins/wapuugotchi
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
    networks:
      - wapuugotchi
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wpcli:
    image: wordpress:cli
    depends_on:
      - db
      - wordpress
    user: xfs
    volumes:
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/plugins/wapuugotchi
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
    command: >
      /bin/sh -c '
      sleep 10;
      wp core install --path="/var/www/html" --url="http://localhost:8076" --title="My WordPress" --admin_user=admin --admin_password=admin --admin_email=admin@local.host;
      wp plugin activate wapuugotchi;
      '
    networks:
      - wapuugotchi

  builder:
    build: https://gitlab.git-wp.server.lan/wp-dev/wordpress-builder.git
    depends_on:
      - wordpress
      - wpcli
    working_dir: /app
    volumes:
      - .:/app
    command: ['npm', 'run', 'grunt', 'build']
    networks:
      - wapuugotchi

volumes:
  wordpress:

networks:
  wapuugotchi:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.120.0/24
